services:
    #form change_password factory
    members.change_password.form.factory:
        class: MembersBundle\Form\Factory\FormFactory
        arguments:
            - '@form.factory'
            - 'members_user_registration_form'
            - 'MembersBundle\Form\Type\ChangePasswordFormType'
            - [Registration, Default]

    #form change_password type
    members.change_password.form.type:
        class: MembersBundle\Form\Type\ChangePasswordFormType
        arguments:
            - '\MembersBundle\Adapter\User\AbstractUser'
        tags:
            - { name: form.type, alias: members_user_change_password }