services:

    # event: check auth
    members.event_listener.authentication:
        class: MembersBundle\EventListener\AuthenticationListener
        arguments:
            - '@members.manager.login'
        tags:
            - { name: kernel.event_subscriber }

    # event: user flash message translations
    members.event_listener.flash:
        class: MembersBundle\EventListener\FlashListener
        arguments:
            - '@session'
            - '@pimcore.translator'
        tags:
            - { name: kernel.event_subscriber }

    # event: user resetting: post add and update events of objects, assets, documents.
    members.event_listener.resetting:
        class: MembersBundle\EventListener\ResettingListener
        arguments:
            - '@router'
            - '%members.resetting.token_ttl%'
        tags:
            - { name: kernel.event_subscriber }

    # listen to routes and redirect them if necessary
    members.event_listener.forbidden_route:
        class: MembersBundle\EventListener\ForbiddenRouteListener
        arguments:
            - '@members.manager.restriction'
            - '@router'
            - '@pimcore.http.request_helper'
        tags:
            - { name: kernel.event_subscriber }

     # event: adds groups meta tags to HeadMeta view helper
    members.event_listener.frontend.document_head_meta:
        class: MembersBundle\EventListener\Frontend\HeadMetaListener
        arguments:
            - '@members.manager.restriction'
            - '@pimcore.service.request.document_resolver'
            - '@pimcore.templating.view_helper.head_meta'
        tags:
            - { name: kernel.event_subscriber }

    # that's not nice. is there a better way?
    members.event_listener.post_confirmation:
        class: MembersBundle\EventListener\PostConfirmationListener
        arguments:
            - '@members.mailer'
            - '@router'
            - '@session'
            - '@members.tool.token_generator'
            - '%members.registration.event.type%'
        tags:
            - { name: kernel.event_subscriber }

    # event: post add and update events of objects, assets, documents.
    members.event_listener.restriction_store:
        class: MembersBundle\EventListener\RestrictionStoreListener
        arguments:
            - '@request_stack'
            - '@members.service.restriction'
        tags:
            - { name: kernel.event_subscriber }

    # event: listen to changes on user updates. send mails if available.
    members.event_listener.user_change:
        class: MembersBundle\EventListener\UserChangeListener
        arguments:
            - '@members.mailer'
        tags:
            - { name: kernel.event_subscriber }