services:

    #form registration factory
    members.registration.form.factory:
        class: MembersBundle\Form\Factory\FormFactory
        arguments:
            - '@form.factory'
            - 'members_user_registration_form'
            - 'MembersBundle\Form\Type\RegistrationFormType'
            - [Registration, Default]

    #form registration type
    members.registration.form.type:
        class: MembersBundle\Form\Type\RegistrationFormType
        arguments:
            - '\MembersBundle\Adapter\User\AbstractUser'
        tags:
            - { name: form.type, alias: members_user_registration }

    # that's not nice. is there a better way?
    members.event_listener.post_confirmation:
        class: MembersBundle\EventListener\PostConfirmationListener
        arguments:
            - '@members.mailer'
            - '@router'
            - '@session'
            - '@members.tool.token_generator'
            - '%members.registration.event.type%'
        tags:
            - { name: kernel.event_subscriber }