# frontend login / logout
members_user_security_login:
    path: /login
    defaults: { _controller: MembersBundle:Auth:login }
    methods:  [GET, POST]
members_user_security_check:
    path: /login_check
    defaults: { _controller: MembersBundle:Auth:check }
    methods:  [POST]
members_user_security_logout:
    path: /logout
    defaults: { _controller: MembersBundle:Auth:logout }
    methods:  [GET, POST]