imports:
    - { resource: services/*.yml }

services:

    # configuration
    members.configuration:
        class: MembersBundle\Configuration\Configuration
        arguments:
            - '@pimcore.extension.bundle_manager'

    # session: configurator
    members.session.configurator:
        class: MembersBundle\Session\SessionConfigurator
        tags:
            - { name: pimcore.session.configurator }

     # security: restriction uri parser
    members.security.restriction.uri:
        class: MembersBundle\Security\RestrictionUri
        arguments:
             - '@members.manager.restriction'

     # security: restriction query parser
    members.security.restriction.query:
        class: MembersBundle\Security\RestrictionQuery
        arguments:
             - '@members.manager.restriction'

    # security: password encoder
    members.security.password_encoder_factory:
        class: Pimcore\Security\Encoder\Factory\UserAwareEncoderFactory
        arguments:
            - Pimcore\Security\Encoder\PasswordFieldEncoder
            - ['password']

    # validator constraints
    members.validator.email_already_exist:
            class: MembersBundle\Validator\Constraints\IsUniqueEmail

    # validator constraints
    members.constraint.email_already_exist:
        class: MembersBundle\Validator\Constraints\IsUniqueEmailValidator
        arguments:
            - '@members.manager.user'
        tags:
            - { name: validator.constraint_validator, alias: members.constraint.email_already_exist }