# frontend registration
members_user_registration_register:
    path: /
    defaults: { _controller: MembersBundle:Registration:register }
members_user_registration_check_email:
    path: /check-email
    defaults: { _controller: MembersBundle:Registration:checkEmail }
members_user_registration_check_admin:
    path: /check-admin
    defaults: { _controller: MembersBundle:Registration:checkAdmin }
members_user_registration_confirm:
    path: /confirm/{token}
    defaults: { _controller: MembersBundle:Registration:confirm }
members_user_registration_confirmed:
    path: /confirmed
    defaults: { _controller: MembersBundle:Registration:confirmed }