services:
    members.brick.builder:
        class: MembersBundle\Document\Builder\BrickBuilder
        shared: false
        arguments:
            - '@security.token_storage'
            - '@pimcore.templating.include_renderer'
            - '@router'

    members.area.brick.login:
        class: MembersBundle\Document\Areabrick\MembersLogin\MembersLogin
        arguments:
            - '@members.brick.builder'
            - '@members.security.login.form.factory'
        tags:
            - { name: pimcore.area.brick, id: members_login }