services:

    #form change_password factory
    members.change_password.form.factory:
        public: true
        class: MembersBundle\Form\Factory\FormFactory
        arguments:
            - '@form.factory'
            - '%members_user.change_password.form.name%'
            - '%members_user.change_password.form.type%'
            - '%members_user.change_password.form.validation_groups%'

    #form change_password type
    members.change_password.form.type:
        class: MembersBundle\Form\Type\ChangePasswordFormType
        arguments:
            - '\MembersBundle\Adapter\User\UserInterface'
        tags:
            - { name: form.type, alias: members_user_change_password }