services:

    # tool: installer
    members.tool.installer:
        class: MembersBundle\Tool\Install
        arguments:
            - '@pimcore_admin.security.token_storage_user_resolver'
            - '@pimcore_admin.serializer'

    # tool: installer
    members.tool.token_generator:
        class: MembersBundle\Tool\TokenGenerator