services:
    members.twig.extension.navigation:
        class: MembersBundle\Twig\Extension\NavigationExtension
        arguments:
            - '@pimcore.templating.view_helper.navigation'
            - '@members.manager.restriction'
            - '@security.token_storage'
        public: false
        tags:
            - { name: twig.extension }
    members.twig.extension.restriction_uri:
        class: MembersBundle\Twig\Extension\RestrictionUriExtension
        arguments:
            - '@members.security.restriction.uri'
        public: false
        tags:
            - { name: twig.extension }