services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MembersBundle\Twig\Extension\NavigationExtension:
        tags:
            - { name: twig.extension }

    MembersBundle\Twig\Extension\RestrictionUriExtension:
        tags:
            - { name: twig.extension }