members.controller.admin.get_restriction_config:
    path: /admin/members/restriction/get-document-restriction-config
    defaults: { _controller: MembersBundle:Admin\Restriction:getDocumentRestrictionConfig }
members.controller.admin.set_document_restriction:
    path: /admin/members/restriction/set-document-restriction-config
    defaults: { _controller: MembersBundle:Admin\Restriction:setDocumentRestrictionConfig }
members.controller.admin.get_global_settings:
    path: /admin/members/restriction/get-global-settings
    defaults: { _controller: MembersBundle:Admin\Restriction:getGlobalSettings }
members.controller.admin.get_groups:
    path: /admin/members/restriction/get-groups
    defaults: { _controller: MembersBundle:Admin\Restriction:getGroups }
members.controller.admin.get_next_parent_restriction:
    path: /admin/members/restriction/get-next-parent-restriction
    defaults: { _controller: MembersBundle:Admin\Restriction:getNextParentRestriction }
members.controller.admin.delete_document_restriction_config:
    path: /admin/members/restriction/delete-document-restriction-config
    defaults: { _controller: MembersBundle:Admin\Restriction:deleteDocumentRestrictionConfig }
members.asset_request:
    path: /members/request-data/{hash}
    defaults: { _controller: MembersBundle:Request:serve }